"""add current_stage to recommendations

Revision ID: 898afcc6760f
Revises: eab106436ea4
Create Date: 2026-08-27 02:04:30.889806

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "898afcc6760f"
down_revision: Union[str, Sequence[str], None] = "eab106436ea4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recommendations", sa.Column("current_stage", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recommendations", "current_stage")
    # ### end Alembic commands ###
