"""recommendations and feature snapshots

Revision ID: bc3015230763
Revises: cf669b73e005
Create Date: 2026-08-27 01:28:29.777023

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bc3015230763"
down_revision: Union[str, Sequence[str], None] = "cf669b73e005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommendations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("topic", sa.String(), nullable=True),
        sa.Column("angle", sa.String(), nullable=True),
        sa.Column("format", sa.String(), nullable=True),
        sa.Column("composite_score", sa.Numeric(), nullable=True),
        sa.Column("evidence_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("selection_type", sa.String(), nullable=True),
        sa.Column("content_package", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("baseline_picks", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("expected_engagement_prediction", sa.Numeric(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["creators.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feature_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recommendation_id", sa.Uuid(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("predicted_engagement", sa.Numeric(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["creators.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feature_snapshots")
    op.drop_table("recommendations")
    # ### end Alembic commands ###
