"""add outcomes table

Revision ID: 76e74183f8b9
Revises: 898afcc6760f
Create Date: 2026-08-27 02:33:54.739199

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "76e74183f8b9"
down_revision: Union[str, Sequence[str], None] = "898afcc6760f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outcomes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recommendation_id", sa.Uuid(), nullable=False),
        sa.Column("reel_id", sa.Uuid(), nullable=False),
        sa.Column("topic_match_score", sa.Numeric(), nullable=True),
        sa.Column("actual_engagement_rate", sa.Numeric(), nullable=True),
        sa.Column("predicted_engagement", sa.Numeric(), nullable=True),
        sa.Column("selection_type", sa.String(), nullable=True),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reel_id"],
            ["reels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recommendation_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outcomes")
    # ### end Alembic commands ###
