"""make instagram fields nullable for pre-connect creators

Revision ID: fe4bdc4cefcd
Revises: 79bef2b15650
Create Date: 2026-08-27 03:03:25.522833

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fe4bdc4cefcd"
down_revision: Union[str, Sequence[str], None] = "79bef2b15650"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("creators", "instagram_user_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("creators", "display_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("creators", "token", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "creators",
        "token_expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "creators",
        "token_expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column("creators", "token", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("creators", "display_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("creators", "instagram_user_id", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
